// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@3.0.4";

// src/lib/mcp/tools/search-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z } from "npm:zod@^4.6.5";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var notAuthed = () => ({
  content: [{ type: "text", text: "Not authenticated" }],
  isError: true
});

// src/lib/mcp/tools/search-products.ts
var search_products_default = defineTool({
  name: "search_products",
  title: "Cari produk & stok",
  description: "Search active products by name or SKU and return their on-hand stock totals.",
  inputSchema: {
    query: z.string().trim().max(100).optional().describe("Name or SKU fragment; empty lists all."),
    limit: z.number().int().min(1).max(100).optional().describe("Max rows (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    const sb = supabaseForUser(ctx);
    let q = sb.from("products").select("id, sku, name, min_stock, location_rack, inventory_batches(batch_no, qty_on_hand, expired_date)").eq("is_active", true).is("deleted_at", null).order("name").limit(limit ?? 25);
    if (query) {
      const safe = query.replace(/[%,()]/g, " ");
      q = q.or(`name.ilike.%${safe}%,sku.ilike.%${safe}%`);
    }
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const products = (data ?? []).map((p) => {
      const batches = (p.inventory_batches ?? []).map((b) => ({
        batch_no: b.batch_no,
        qty_on_hand: Number(b.qty_on_hand),
        expired_date: b.expired_date
      }));
      return {
        id: p.id,
        sku: p.sku,
        name: p.name,
        location_rack: p.location_rack,
        min_stock: p.min_stock,
        qty_on_hand: batches.reduce((s, b) => s + b.qty_on_hand, 0),
        batches
      };
    });
    return { content: [{ type: "text", text: JSON.stringify(products) }], structuredContent: { products } };
  }
});

// src/lib/mcp/tools/list-sales-orders.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z as z2 } from "npm:zod@^4.6.5";
var list_sales_orders_default = defineTool2({
  name: "list_sales_orders",
  title: "Daftar Sales Order",
  description: "List recent Sales Orders, optionally filtered by status or order number.",
  inputSchema: {
    status: z2.string().trim().max(40).optional().describe("e.g. draft, approved, delivered, cancelled"),
    number: z2.string().trim().max(60).optional().describe("Fragment of the SO number"),
    limit: z2.number().int().min(1).max(100).optional().describe("Max rows (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, number, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    const sb = supabaseForUser(ctx);
    let q = sb.from("sales_order_headers").select("id, sales_order_number, order_date, delivery_deadline, status, order_type, sales_name, project_instansi, grand_total, customers(name)").or("is_deleted.is.null,is_deleted.eq.false").order("order_date", { ascending: false }).limit(limit ?? 25);
    if (status) q = q.eq("status", status);
    if (number) q = q.ilike("sales_order_number", `%${number.replace(/[%]/g, "")}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const orders = (data ?? []).map((o) => ({
      id: String(o.id),
      number: String(o.sales_order_number),
      order_date: o.order_date,
      delivery_deadline: o.delivery_deadline,
      status: String(o.status),
      order_type: String(o.order_type),
      sales_name: String(o.sales_name),
      project: String(o.project_instansi),
      customer: o.customers?.name ?? null,
      grand_total: o.grand_total == null ? null : Number(o.grand_total)
    }));
    return { content: [{ type: "text", text: JSON.stringify(orders) }], structuredContent: { orders } };
  }
});

// src/lib/mcp/tools/list-plan-orders.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z as z3 } from "npm:zod@^4.6.5";
var list_plan_orders_default = defineTool3({
  name: "list_plan_orders",
  title: "Daftar Plan Order",
  description: "List recent inbound Plan Orders, optionally filtered by status.",
  inputSchema: {
    status: z3.string().trim().max(40).optional().describe("e.g. draft, approved, received"),
    limit: z3.number().int().min(1).max(100).optional().describe("Max rows (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    const sb = supabaseForUser(ctx);
    let q = sb.from("plan_order_headers").select("id, plan_number, plan_date, expected_delivery_date, status, grand_total, suppliers(name)").order("plan_date", { ascending: false }).limit(limit ?? 25);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const orders = (data ?? []).map((o) => ({
      id: String(o.id),
      number: String(o.plan_number),
      plan_date: o.plan_date,
      expected_delivery_date: o.expected_delivery_date ?? null,
      status: String(o.status),
      supplier: o.suppliers?.name ?? null,
      grand_total: o.grand_total == null ? null : Number(o.grand_total)
    }));
    return { content: [{ type: "text", text: JSON.stringify(orders) }], structuredContent: { orders } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "yzlfqllwusfnhigtezfo";
var mcp_default = defineMcp({
  name: "warehouse-management-inventory",
  title: "Warehouse Management Inventory",
  version: "0.1.0",
  instructions: "Read-only tools for the PT. Kemika Karya Pratama WMS. Use `search_products` for stock levels, `list_sales_orders` for outbound orders, and `list_plan_orders` for inbound orders. Data access follows the signed-in user's role.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_products_default, list_sales_orders_default, list_plan_orders_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.4/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
